/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_RAMDualPort
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
  input [(AddrBits-1):0] A,
  input [(Bits-1):0] Din,
  input str,
  input C,
  input ld,
  output [(Bits-1):0] D
);
  reg [(Bits-1):0] memory[0:((1 << AddrBits) - 1)];

  assign D = ld? memory[A] : 'hz;

  always @ (posedge C) begin
    if (str)
      memory[A] <= Din;
  end
endmodule


module program_ram (
  input [3:0] addr,
  input [3:0] data_in,
  input write,
  input clk,
  output [3:0] data_out
);
  // program\_ram
  DIG_RAMDualPort #(
    .Bits(4),
    .AddrBits(4)
  )
  DIG_RAMDualPort_i0 (
    .A( addr ),
    .Din( data_in ),
    .str( write ),
    .C( clk ),
    .ld( 1'b1 ),
    .D( data_out )
  );
endmodule
